[2016-11-16 23:10:08 +0000] [2161] [INFO] Starting gunicorn 19.6.0
[2016-11-16 23:10:08 +0000] [2161] [INFO] Listening at: http://0.0.0.0:8000 (2161)
[2016-11-16 23:10:08 +0000] [2161] [INFO] Using worker: sync
[2016-11-16 23:10:08 +0000] [2171] [INFO] Booting worker with pid: 2171
[2016-11-16 23:10:08 +0000] [2171] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/lib/python2.6/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.6/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
ImportError: Import by filename is not supported.
[2016-11-16 23:10:08 +0000] [2171] [INFO] Worker exiting (pid: 2171)
[2016-11-16 23:10:08 +0000] [2161] [INFO] Shutting down: Master
[2016-11-16 23:10:08 +0000] [2161] [INFO] Reason: Worker failed to boot.
[2016-11-16 23:11:21 +0000] [2213] [INFO] Starting gunicorn 19.6.0
[2016-11-16 23:11:21 +0000] [2213] [INFO] Listening at: http://0.0.0.0:8000 (2213)
[2016-11-16 23:11:21 +0000] [2213] [INFO] Using worker: sync
[2016-11-16 23:11:21 +0000] [2223] [INFO] Booting worker with pid: 2223
[2016-11-16 23:11:21 +0000] [2223] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/lib/python2.6/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.6/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
ImportError: No module named ask.wsgi
[2016-11-16 23:11:21 +0000] [2223] [INFO] Worker exiting (pid: 2223)
[2016-11-16 23:11:21 +0000] [2213] [INFO] Shutting down: Master
[2016-11-16 23:11:21 +0000] [2213] [INFO] Reason: Worker failed to boot.
